---
title: "Interacting with naturaList: the map_module() function "
author: "Gabriel Nakamura"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{article_mapmodule}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Interactivelly exploring and editing occurrence data
In this article the user can explore the interactive module presented in naturaList package: the `map_module` function. 
Through `map_module` the user will be able to visual explore the occurrence data by seeing how it is distributed in space, as described in Figure 1.

## Check out for records in a interactive map module

The `map_module()` function allow the user to visualize the occurrence records in a interactive map. In this interactive map, the user can click over an occurence point to see basic information about the record, such as the instituition that holds the record, who identified the species and when it was identified. Also, if some error is identified, the user could allow that clicking works to delete points.


![Fig. 2 - Features of `map_module()` function used in the example with Alsophila setosa occurrence data. A) the initial display of occurrence records data; B) highlights the features of map\_module. I -- Select levels to be maintained in the output dataset; II -- enable to delete point with click over occurrences; III -- show how many points have been selected from the initial dataset; IV -- display in the map only occurrences that belong to the selected levels, and turn visualization of the map between OpenStreetMap and Satelite; V -- options to draw and edit polygons to select occurrence records that fall within polygon; X -- highlights the deleted occurrence points](../vignettes/fig_map_module.png)


In the figure 2, you see two screen shots from `map_module()`. In figure 2A, it is showed the initial display of occurence records. In figure 2B it is highlighted the features inside `map_module()`.

In this example, we selected the levels 1 and 2 (Fig 2B - I). Then we deleted three records, by setting on the button *delete points with click* (Fig 2B - II) and clicking on them. At the end of selection we click on 'Done !' button.

Other features are avalible and can be seen on the figure 2. Try out with this example dataset.
